version: '3'
services:
  nginx:
    image: nginx:1.15.8-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    build: 
      context: ./
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env